export const strings = {
    pt: {
        app_name: "Receitas do Casal",
        add_recipe: "Nova Receita",
        search_hint: "Buscar receitas...",
        no_recipes: "Nenhuma receita encontrada. Que tal adicionar uma?",
        cancel: "Cancelar",
        save: "Salvar",
        back: "Voltar",
        settings_title: "Configurações",
        data_management_title: "Gerenciamento de Dados",
        create_backup: "Criar Backup",
        restore_backup: "Restaurar Backup",
        backup_success: "Backup salvo com sucesso!",
        restore_success: "Backup restaurado com sucesso!",
        other_options_title: "Outras Opções",
        print_recipe_book: "Imprimir Livro de Receitas",
        privacy_policy_title: "Política de Privacidade",
        select_language: "Idioma / Language",
        privacy_header: "Política de Privacidade",
        privacy_last_update: "Última atualização: Dezembro de 2025",
        privacy_intro: "Certifique-se de ter lido e entendido as disposições aqui contidas antes de iniciar a utilização deste aplicativo para gestão de receitas do casal. Em caso de dúvidas, basta enviar uma mensagem para o e-mail: ers-labs@outlook.com.\n\nSe você não ler, entender e concordar integralmente com esta Política de Privacidade, você deve evitar ou suspender o uso deste aplicativo.",
        privacy_personal_info_title: "Informações Pessoais",
        privacy_personal_info_body: "Este aplicativo prioriza sua privacidade. Nós não coletamos nenhuma informação pessoal (como nome, endereço de e-mail ou número de telefone) de seus usuários. Todo o conteúdo criado no aplicativo, como suas receitas e anotações, é armazenado localmente no seu dispositivo. Não é necessário criar uma conta ou fazer login em servidores externos para utilizar as funcionalidades principais do aplicativo.",
        privacy_device_title: "Informações do Dispositivo e Localização",
        privacy_device_body: "Identificação: Este aplicativo não coleta nenhuma informação referente ao modelo, número de série ou endereço de rede (número IP) de seu dispositivo móvel para fins de rastreamento de usuário.\n\nLocalização: Este aplicativo não coleta nenhuma informação sobre a localização geográfica de seu dispositivo móvel.",
        privacy_camera_title: "Câmera e Mídia",
        privacy_camera_body: "O aplicativo utiliza a câmera e o acesso à galeria do seu dispositivo estritamente para que você possa personalizar suas receitas:\n\n• As fotos e vídeos adicionados às receitas são armazenados localmente no seu dispositivo.\n• Esses arquivos de mídia não são enviados para nenhum servidor proprietário do aplicativo.",
        privacy_backup_title: "Cópias de Segurança (Backup)",
        privacy_backup_body: "O aplicativo oferece uma funcionalidade de Backup e Restauração para proteger seus dados:\n\n• Ao criar um backup, o aplicativo gera um arquivo (ZIP) contendo suas receitas e mídias.\n• Este arquivo é salvo no local que você escolher dentro do seu dispositivo (ou em sua nuvem pessoal, caso utilize um gerenciador de arquivos integrado).\n• Nós não temos acesso, não coletamos e não armazenamos seus arquivos de backup. O gerenciamento desses arquivos é de sua exclusiva responsabilidade.",
        privacy_ads_title: "Propagandas",
        privacy_ads_body: "Este aplicativo pode trabalhar com anunciantes e redes de publicidade de terceiros (como Google AdMob) para ajudar a manter o aplicativo gratuito:\n\n• Esses serviços podem coletar dados anônimos sobre sua interação com publicidade e informações da conexão de internet do seu dispositivo para determinar a exibição de anúncios relevantes.\n• Esse controle é feito inteiramente pelos serviços de anúncios; nenhuma informação pessoal é armazenada diretamente pelo código do aplicativo \"Receitas do Casal\".",
        privacy_permissions_title: "Permissões Solicitadas",
        privacy_permissions_body: "Câmera: Utilizada apenas quando você opta por tirar uma foto ou gravar um vídeo para uma receita.\n\nArmazenamento: Utilizada para salvar as mídias das suas receitas e para ler/gravar os arquivos de backup.",
        delete_recipe_title: "Excluir Receita?",
        delete_recipe_message: "Tem certeza que deseja apagar essa receita para sempre?",
        delete_button: "Apagar",
        ingredients: "Ingredientes",
        instructions: "Modo de Preparo",
        recipes_title: "Minhas Receitas",
        new_recipe_title: "Nova Receita",
        edit_recipe_title: "Editar Receita",
        name_label: "Nome da Receita",
        media_label: "Fotos e Vídeos",
        install_app: "Instalar App",
        enter_app: "Entrar no App",
        landing_subtitle: "Salve, compartilhe e cozinhe com quem você ama.\nUse offline, grave vídeos e muito mais.",
        advertisement: "Publicidade"
    },
    en: {
        app_name: "Recipe for Lovers",
        add_recipe: "New Recipe",
        search_hint: "Search recipes...",
        no_recipes: "No recipes found. How about adding one?",
        cancel: "Cancel",
        save: "Save",
        back: "Back",
        settings_title: "Settings",
        data_management_title: "Data Management",
        create_backup: "Create Backup",
        restore_backup: "Restore Backup",
        backup_success: "Backup saved successfully!",
        restore_success: "Backup restored successfully!",
        other_options_title: "Other Options",
        print_recipe_book: "Print Recipe Book",
        privacy_policy_title: "Privacy Policy",
        select_language: "Language",
        privacy_header: "Privacy Policy",
        privacy_last_update: "Last Updated: December 2025",
        privacy_intro: "Please ensure you have read and understood the provisions contained herein before managing your couple's recipes. If in doubt, email: ers-labs@outlook.com.",
        privacy_personal_info_title: "Personal Information",
        privacy_personal_info_body: "We do not collect personal info. All content is stored locally on your device.",
        privacy_device_title: "Device Info & Location",
        privacy_device_body: "We do not collect device info or location data.",
        privacy_camera_title: "Camera & Media",
        privacy_camera_body: "Camera is used strictly for personalizing recipes. Media is stored locally.",
        privacy_backup_title: "Backups",
        privacy_backup_body: "Backups are zip files stored locally. We do not access them.",
        privacy_ads_title: "Ads",
        privacy_ads_body: "Third-party ad networks may collect anonymous data.",
        privacy_permissions_title: "Permissions",
        privacy_permissions_body: "Camera: For photos/videos. Storage: For saving content.",
        delete_recipe_title: "Delete Recipe?",
        delete_recipe_message: "Are you sure you want to delete this recipe forever?",
        delete_button: "Delete",
        ingredients: "Ingredients",
        instructions: "Instructions",
        recipes_title: "My Recipes",
        new_recipe_title: "New Recipe",
        edit_recipe_title: "Edit Recipe",
        name_label: "Recipe Name",
        media_label: "Photos & Videos",
        install_app: "Install App",
        enter_app: "Enter App",
        landing_subtitle: "Save, share and cook with the one you love.\nUse offline, record videos and more.",
        advertisement: "Advertisement"
    }
};
